GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjY1NzVlMDU1YjE1ODFmMTJlOGM1Yjg1ZCIsImlhdCI6MTcwOTgxMjE0OX0.rF6L4zP6I6-i9nkBdkwGdNbD_HZ_Om-hvhyfdaZusRs

{
    "title": "OTRO 2",
    "author": "rogeliomdn",
    "url": "https://github.com/rogmed/helsinki-fullstack",
    "likes": 500
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "POSTTTTT",
    "author": "Matti Luukkainen",
    "url": "https://fullstackopen.com/en/",
    "likes": 900000,
    "userId": "6571d4e10104b2d35495f326"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Cosas de casa",
    "author": "Rogelio Medina",
    "url": "https://fullstackopen.com/en/",
    "likes": 77777,
    "userId": "6571d4e10104b2d35495f326"
}

###
PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
content-type: application/json

{
    "likes": 400
}

###
DELETE http://localhost:3003/api/blogs/6575d8ccdd1088b0c8b1ec99
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvZ2VsaW9tZG4iLCJpZCI6IjY1NzVkODgzZGQxMDg4YjBjOGIxZWM4ZCIsImlhdCI6MTcwMjIyMjAwNH0.q0rURUPq-6Ojkq3Gi6NeOUmyGbjnti201II45ucBhBs
