GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Helsinki Fullstack",
    "author": "rogeliomdn",
    "url": "https://github.com/rogmed/helsinki-fullstack",
    "likes": 500,
    "userId": "6571d4e10104b2d35495f326"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "POSTTTTT",
    "author": "Matti Luukkainen",
    "url": "https://fullstackopen.com/en/",
    "likes": 900000,
    "user": "6571c1589298dba48489c00f"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Cosas de casa",
    "author": "Rogelio Medina",
    "url": "https://fullstackopen.com/en/",
    "likes": 77777,
    "user": "6571d4e10104b2d35495f326"
}

###
PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
content-type: application/json

{
    "likes": 400
}
