GET http://localhost:3003/api/blogs

###
POST http://localhost:3003/api/blogs
content-type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvZ2VsaW9tZG4iLCJpZCI6IjY1NzFmYjVkZjY2ZGIzNDRlNTQ1OWZhMyIsImlhdCI6MTcwMTk2ODc0NH0.RbpZEjXmWCYMgmE72PD_uyL0UiKe4YavcxX34QXrqTs

{
    "title": "OTRO 2",
    "author": "rogeliomdn",
    "url": "https://github.com/rogmed/helsinki-fullstack",
    "likes": 500
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "POSTTTTT",
    "author": "Matti Luukkainen",
    "url": "https://fullstackopen.com/en/",
    "likes": 900000,
    "userId": "6571d4e10104b2d35495f326"
}

###
POST http://localhost:3003/api/blogs
content-type: application/json

{
    "title": "Cosas de casa",
    "author": "Rogelio Medina",
    "url": "https://fullstackopen.com/en/",
    "likes": 77777,
    "userId": "6571d4e10104b2d35495f326"
}

###
PUT http://localhost:3003/api/blogs/5a422a851b54a676234d17f7
content-type: application/json

{
    "likes": 400
}
