GET http://localhost:3003/api/users

###
POST http://localhost:3003/api/users
content-type: application/json

{
    "username": "rogeliomdn",
    "name": "Rogelio Medina",
    "password": "12345678"
}